cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace=' shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, unique=True)


	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
	category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE) 
	name = models.CharField(max_length=200, db_index=True) 
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	link = models.CharField(max_length=2055, default='')
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2) 
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)


	class Meta:
		ordering = ('name',) 
		index_together = (('id', 'slug'),)
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    # product = Product.objects.get(id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

# def cart_add(request, product_id):
#     if request.method == "POST":
#         cart = Cart(request)
#         product = Product.objects.get(id=product_id)
#         form = CartAddProductForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
#         return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None): 
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True) 
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category) 
	return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()
	return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
<!--                <img src="{% if product.image %}{{ product.image.url }}-->
<!--                {%endif%}">-->
                <img src="{{product.link}}" alt="">
            </a>
        </td>
        <td>{{product.name}}</td>
        <td>{{item.quantity}}</td>
        <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
        <td class="num">${{item.price}}</td>
        <td class="num">${{item.total_price}}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
    <a href="#" class="button">Checkout</a>
</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>ZSHOP</title>
</head>
<meta charset="utf-8"/>
<title>{% block title %}My shop{% endblock %}</title>
<link href="{% static ' css/base.css' %}" rel="stylesheet">

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">ZSHOP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'shop:product_list' %}">All</a>
                    {% for c in categories %}
                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    {% endfor %}
                    <!--          <a class="dropdown-item" href="#">Another action</a>-->
                    <!--          <div class="dropdown-divider"></div>-->
                    <!--          <a class="dropdown-item" href="#">Something else here</a>-->
                </div>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <!--<div id="header">-->
    <!--    <a href="/" class="logo">My shop</a>-->
    <!--</div>-->
    <div id="subheader">
        <div class="cart">
            <h3 class="badge badge-primary text-wrap" style="width: 6rem;"> Your cart is empty </h3>
        </div>
    </div>
    <div id="content" class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/product/categories.html
 <li><a href="{% url 'shop:product_list' %}">All</a></li>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %} {% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <!--    <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static " img/no_image.png" %}{% endif %}">-->
    <img align="right" src="{{product.link}}" height="556" width="470">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url  'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>

    {{ product.description|linebreaks }}

</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% block content %}
{% load static %}
{% block title %}
{% endblock %}
<div id="sidebar">
<!--    <div class="dropdown">-->
<!--        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"-->
<!--                aria-haspopup="true" aria-expanded="false">-->
<!--            Categories-->
<!--        </button>-->
<!--        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">-->
<!--            <li><a href="{% url ' shop:product_list' %}">All</a></li>-->
<!--            &lt;!&ndash;        <ul>&ndash;&gt;-->
<!--            {% for c in categories %}-->
<!--            &lt;!&ndash;        <li {% if category.slug == c.slug %}class="selected"&ndash;&gt;-->
<!--            &lt;!&ndash;            {% endif %}>&ndash;&gt;-->
<!--            <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>-->
<!--            {% endfor %}-->
<!--            &lt;!&ndash;    <a class="dropdown-item" href="#">Action</a>&ndash;&gt;-->
<!--            &lt;!&ndash;    <a class="dropdown-item" href="#">Another action</a>&ndash;&gt;-->
<!--            &lt;!&ndash;    <a class="dropdown-item" href="#">Something else here</a>&ndash;&gt;-->
<!--        </div>-->
<!--    </div>-->
    <!--    <h3>Categories</h3>-->
    <!--    <ul>-->
    <!--&lt;!&ndash;        <li {% if not category %}class="selected" {% endif %}>&ndash;&gt;-->
    <!--            <li><a href="{% url ' shop:product_list' %}">All</a></li>-->
    <!--&lt;!&ndash;        <ul>&ndash;&gt;-->
    <!--            {% for c in categories %}-->
    <!--&lt;!&ndash;        <li {% if category.slug == c.slug %}class="selected"&ndash;&gt;-->
    <!--        &lt;!&ndash;            {% endif %}>&ndash;&gt;-->
    <!--            <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>-->
    <!--        {% endfor %}-->
    <!--        </ul>-->
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products {% endif %}</h1>
    <div class="row">
        {% for product in products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="{{product.link}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <!--    <h5 class="card-title">Card title</h5>-->
                    <!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">{{ product.name }}</a>
                    <!--  </div>-->
                    <!--    <div class="item">-->
                    <!--        <a href="{{ product.get_absolute_url }}">-->
                    <!--            <img src="{% if product.image %}{{ product.image.url }}{%-->
                    <!--else %}{% static ' img/no_image.png' %}{% endif %}"> </a>-->
                    <!--        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> <br>-->
                    <!--        ${{ product.price }}-->
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
{% endblock %}